# Generated by Django 5.0 on 2025-11-24 00:49

from django.db import migrations
from django.contrib.auth.models import User


def create_admin_user(apps, schema_editor):
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'admin')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
